CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department VARCHAR(120) NOT NULL CHECK (btrim(department) <> ''),
    building VARCHAR(120),
    floor VARCHAR(50),
    room VARCHAR(80),
    description VARCHAR(1000),
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE printers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand VARCHAR(100) NOT NULL CHECK (btrim(brand) <> ''),
    model VARCHAR(120) NOT NULL CHECK (btrim(model) <> ''),
    serial_number VARCHAR(120),
    sticker_number VARCHAR(80) NOT NULL CHECK (btrim(sticker_number) <> ''),
    location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE RESTRICT,
    status VARCHAR(30) NOT NULL CHECK (status IN (
        'ACTIVE', 'UNDER_REPAIR', 'FOR_REPAIR', 'STORAGE', 'RETIRED', 'DISPOSED'
    )),
    remarks VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0
);

-- Deleted printers also reserve their identifiers. Serial numbers may be unknown (NULL).
CREATE UNIQUE INDEX uk_printers_sticker ON printers (upper(btrim(sticker_number)));
CREATE UNIQUE INDEX uk_printers_serial ON printers (upper(btrim(serial_number)))
    WHERE serial_number IS NOT NULL;
CREATE INDEX idx_printers_location ON printers (location_id);
CREATE INDEX idx_printers_status_live ON printers (status) WHERE deleted_at IS NULL;
CREATE INDEX idx_printers_brand_live ON printers (lower(brand)) WHERE deleted_at IS NULL;
