CREATE TABLE relocation_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    printer_id BIGINT NOT NULL REFERENCES printers(id) ON DELETE RESTRICT,
    previous_location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE RESTRICT,
    new_location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE RESTRICT,
    relocation_date DATE NOT NULL,
    remarks VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK (previous_location_id <> new_location_id)
);

CREATE INDEX idx_relocations_printer_date ON relocation_history (printer_id, relocation_date DESC, id DESC);
CREATE INDEX idx_relocations_previous_location ON relocation_history (previous_location_id);
CREATE INDEX idx_relocations_new_location ON relocation_history (new_location_id);
